# Generated by Django 4.2.23 on 2026-03-27 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('nom_ferme', models.CharField(max_length=200, verbose_name='Nom de la ferme')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=300)),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='No téléphone')),
                ('cellulaire', models.CharField(blank=True, max_length=20, verbose_name='No cellulaire')),
                ('courriel', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
                ('vendeur', models.ForeignKey(blank=True, limit_choices_to={'role': 'vendeur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_assignes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom_ferme'],
            },
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_culture', models.CharField(choices=[('mais', 'Maïs'), ('soya', 'Soya'), ('ble', 'Blé'), ('orge', 'Orge'), ('avoine', 'Avoine'), ('canola', 'Canola'), ('foin', 'Foin'), ('autre', 'Autre')], max_length=20)),
                ('nom_champ', models.CharField(blank=True, max_length=100, verbose_name='Nom du champ')),
                ('superficie_acres', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Superficie (acres)')),
                ('semence', models.CharField(blank=True, max_length=200, verbose_name='Semence utilisée')),
                ('population_visee', models.IntegerField(blank=True, null=True, verbose_name='Population visée (grains/acre)')),
                ('population_reelle', models.IntegerField(blank=True, null=True, verbose_name='Population réelle (grains/acre)')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultures', to='clients.client')),
            ],
            options={
                'verbose_name': 'Culture',
                'verbose_name_plural': 'Cultures',
                'ordering': ['-annee', 'type_culture'],
            },
        ),
        migrations.CreateModel(
            name='ProduitArrosage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=200)),
                ('dose', models.CharField(max_length=100, verbose_name='Dose par acre')),
                ('quantite_totale', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité totale')),
                ('unite', models.CharField(default='L', max_length=20)),
                ('date_application', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_arrosage', to='clients.culture')),
            ],
            options={
                'verbose_name': "Produit d'arrosage",
                'verbose_name_plural': "Produits d'arrosage",
            },
        ),
    ]
