# Generated by Django 4.2.23 on 2026-03-28 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCulture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Type de culture',
                'verbose_name_plural': 'Types de culture',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterField(
            model_name='culture',
            name='type_culture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cultures', to='clients.typeculture', verbose_name='Type de culture'),
        ),
    ]
