# Generated by Django 4.2.23 on 2026-03-27 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiviPousse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_observation', models.DateField()),
                ('stade_croissance', models.CharField(max_length=100, verbose_name='Stade de croissance')),
                ('hauteur_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Hauteur (cm)')),
                ('densite_plants', models.IntegerField(blank=True, null=True, verbose_name='Densité de plants (plants/acre)')),
                ('etat_general', models.CharField(choices=[('excellent', 'Excellent'), ('bon', 'Bon'), ('moyen', 'Moyen'), ('faible', 'Faible'), ('mauvais', 'Mauvais')], default='bon', max_length=20, verbose_name='État général')),
                ('problemes_observes', models.TextField(blank=True, verbose_name='Problèmes observés')),
                ('photo', models.ImageField(blank=True, upload_to='suivis/')),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis_pousse', to='clients.culture')),
                ('observateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suivi de pousse',
                'verbose_name_plural': 'Suivis de pousse',
                'ordering': ['-date_observation'],
            },
        ),
        migrations.CreateModel(
            name='StatistiqueCulture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rendement_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Rendement estimé (boiss./acre)')),
                ('rendement_reel', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Rendement réel (boiss./acre)')),
                ('taux_germination', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taux de germination (%)')),
                ('cout_total_intrants', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coût total intrants ($)')),
                ('date_semis', models.DateField(blank=True, null=True, verbose_name='Date de semis')),
                ('date_recolte', models.DateField(blank=True, null=True, verbose_name='Date de récolte')),
                ('notes', models.TextField(blank=True)),
                ('culture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistiques', to='clients.culture')),
            ],
            options={
                'verbose_name': 'Statistique de culture',
                'verbose_name_plural': 'Statistiques de culture',
            },
        ),
    ]
