# Generated by Django 4.2.23 on 2026-03-28 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('statut', 'Changement de statut'), ('stock', 'Mise à jour stock'), ('connexion', 'Connexion')], max_length=20)),
                ('entite', models.CharField(help_text='Ex: Commande, Client, Produit', max_length=50)),
                ('entite_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'activité",
                'verbose_name_plural': "Journal d'activité",
                'ordering': ['-date'],
            },
        ),
    ]
