# Generated by Django 4.2.23 on 2026-03-27 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecommande',
            name='date_preparation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='prepare',
            field=models.BooleanField(default=False, verbose_name='Préparé'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='prepare_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_preparees', to=settings.AUTH_USER_MODEL),
        ),
    ]
