# Generated by Django 4.2.23 on 2026-03-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='creee_par_client',
            field=models.BooleanField(default=False, verbose_name='Créée par le client'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('verification', 'En vérification'), ('nouvelle', 'Nouvelle'), ('en_preparation', 'En préparation'), ('prete', 'Prête'), ('en_livraison', 'En livraison'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='nouvelle', max_length=20),
        ),
    ]
