# Generated by Django 4.2.23 on 2026-03-27 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_categorie', models.CharField(choices=[('semence', 'Semence'), ('pesticide', 'Pesticide'), ('engrais_foliaire', 'Engrais foliaire'), ('biostimulant', 'Biostimulant'), ('additif_pulverisation', 'Additif de pulvérisation')], max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Catégorie de produit',
                'verbose_name_plural': 'Catégories de produits',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('format_produit', models.CharField(max_length=100, verbose_name='Format')),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix unitaire')),
                ('en_stock', models.BooleanField(default=True, verbose_name='En stock')),
                ('culture_recommandee', models.CharField(blank=True, help_text='Ex: maïs, soya, blé (séparés par des virgules)', max_length=200, verbose_name='Culture recommandée')),
                ('image', models.ImageField(blank=True, upload_to='produits/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='products.categorieproduit')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['categorie', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='RecommandationProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_culture', models.CharField(max_length=20)),
                ('priorite', models.IntegerField(default=0, help_text='Plus élevé = recommandé en premier')),
                ('description', models.TextField(blank=True, verbose_name='Pourquoi recommander')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='products.produit')),
            ],
            options={
                'verbose_name': 'Recommandation',
                'verbose_name_plural': 'Recommandations',
                'ordering': ['-priorite'],
            },
        ),
    ]
