# Generated by Django 4.2.23 on 2026-03-27 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommandationproduit',
            name='complementaire_de',
            field=models.ForeignKey(blank=True, help_text='Si le client achète ce produit, recommander le produit principal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits_complementaires', to='products.produit'),
        ),
        migrations.AddField(
            model_name='recommandationproduit',
            name='dose_par_acre',
            field=models.CharField(blank=True, help_text='Ex: 1.67 L/acre, 80 000 grains/acre', max_length=100, verbose_name='Dose recommandée par acre'),
        ),
        migrations.AddField(
            model_name='recommandationproduit',
            name='probleme_cible',
            field=models.CharField(blank=True, help_text='Ex: chrysomèle, cercospora, mauvaises herbes résistantes', max_length=200, verbose_name='Problème ciblé'),
        ),
        migrations.AddField(
            model_name='recommandationproduit',
            name='saison',
            field=models.CharField(choices=[('pre_semis', 'Pré-semis (mars-avril)'), ('semis', 'Semis (mai)'), ('post_levee', 'Post-levée (juin)'), ('croissance', 'Croissance (juillet)'), ('floraison', 'Floraison (juillet-août)'), ('recolte', 'Pré-récolte (sept-oct)'), ('toute_saison', 'Toute la saison')], default='toute_saison', max_length=20),
        ),
    ]
