# Generated by Django 4.2.23 on 2026-03-28 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_typeculture_alter_culture_type_culture'),
        ('products', '0002_recommandationproduit_complementaire_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommandationproduit',
            name='type_culture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='clients.typeculture', verbose_name='Type de culture'),
        ),
    ]
