# Generated by Django 4.2.23 on 2026-03-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_recommandationproduit_type_culture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommandationproduit',
            name='dose_par_acre',
        ),
        migrations.AddField(
            model_name='produit',
            name='contenance_unite',
            field=models.CharField(choices=[('L', 'Litres (L)'), ('mL', 'Millilitres (mL)'), ('kg', 'Kilogrammes (kg)'), ('lb', 'Livres (lb)'), ('grains', 'Grains'), ('unite', 'Unité')], default='L', max_length=10, verbose_name='Unité de contenance'),
        ),
        migrations.AddField(
            model_name='produit',
            name='contenance_valeur',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ex: 10 pour un Bidon 10L, 80000 pour un Sac 80000 grains', max_digits=12, null=True, verbose_name='Contenance'),
        ),
        migrations.AddField(
            model_name='produit',
            name='contenant',
            field=models.CharField(choices=[('bidon', 'Bidon'), ('sac', 'Sac'), ('boite', 'Boîte'), ('baril', 'Baril'), ('autre', 'Autre')], default='bidon', max_length=20, verbose_name='Type de contenant'),
        ),
        migrations.AddField(
            model_name='recommandationproduit',
            name='dose_affichage',
            field=models.CharField(blank=True, help_text='Texte affiché: "1.67 L/acre", "1 sac/2 acres"', max_length=100, verbose_name='Dose (affichage)'),
        ),
        migrations.AddField(
            model_name='recommandationproduit',
            name='dose_unite',
            field=models.CharField(blank=True, choices=[('L', 'Litres (L)'), ('mL', 'Millilitres (mL)'), ('kg', 'Kilogrammes (kg)'), ('lb', 'Livres (lb)'), ('grains', 'Grains'), ('unite', 'Unité')], default='', max_length=10, verbose_name='Unité de dose'),
        ),
        migrations.AddField(
            model_name='recommandationproduit',
            name='dose_valeur',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Ex: 1.67, 315, 80000', max_digits=12, null=True, verbose_name='Dose par acre (valeur)'),
        ),
    ]
