# Generated by Django 4.2.23 on 2026-03-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_typeculture_alter_culture_type_culture'),
        ('products', '0004_remove_recommandationproduit_dose_par_acre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='culture_recommandee',
        ),
        migrations.AddField(
            model_name='produit',
            name='cultures_recommandees',
            field=models.ManyToManyField(blank=True, related_name='produits_recommandes', to='clients.typeculture', verbose_name='Cultures recommandées'),
        ),
    ]
