# Generated by Django 4.2.23 on 2026-03-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_produit_culture_recommandee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='quantite_stock',
            field=models.IntegerField(default=0, help_text="Nombre d'unités en stock (sacs, bidons...)", verbose_name='Quantité en inventaire'),
        ),
        migrations.AddField(
            model_name='produit',
            name='seuil_alerte_stock',
            field=models.IntegerField(default=5, help_text='Alerte si le stock descend sous ce seuil', verbose_name="Seuil d'alerte"),
        ),
    ]
